= csoftz-kommit-learn-ror-tutorial :: CSoftZ Kommit Learn Ruby on Rails (RoR) Tutorial

V1.0.3-Apr.18/2017

Holds all of the files involved in the making of the tutorial about Ruby on Rails
at https://www.railstutorial.org/book

A bitbucket repository is found here https://bitbucket.org/railstutorial/sample_app_4th_ed

== docs 

This folder contains the self-contained documentation in Asciidoctor.

== app-code
This folder contains the source code for all of the making of the tutorial.

=== front-end
This folder contains the client-side, normally a web site or Angular site.

=== back-end
This folder contains the server-side.
For the tutorial, this is where all files are to be located.

== Branches
The repository will preserve a bunch of branches to help in discovering the code that 
was developed for each chapter.

The branches are as follows:

* *master:* Holds the production code or the final code for repository.
* *develop:* Holds all of the changes to repository that are not ready for production.
* *feature/learn-ror-ch1:* The steps needed for chapter 1 of the book.
* *feature/learn-ror-ch2:* The steps needed for chapter 2 of the book.