# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e13dd5d0b95f729a42139f9af728b61d875623b145eb1a6a8644de08a1fdcc7ee5855dbb5fd540352236b276c8ffe318731dcbe4e591a7a867856ba2526b638

test:
  secret_key_base: 33daf39ebdab6e29b3d3a7dd4cb356b79ec89603ab1a30ea77f392c7500732198aa0ece0957522e45e82940bdccb98292d484801dbd31c58b12f9690448eb25e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
